/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package io.wangler.micronaut.mailhog

import io.micronaut.test.extensions.spock.annotation.MicronautTest
import jakarta.inject.Inject
import spock.lang.Specification

@MicronautTest
class MailHoqClientSpec extends Specification {


    @Inject
    MailHogClient client

    def "someLibraryMethod returns true"() {
        expect:
        true
    }
}
