name: Release to GitHub Packages

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    services:
      mail:
        image: mailhog/mailhog
        ports:
          - "8025:8025"
          - "21025:1025"

    env:
      M2_USER: ${{ secrets.M2_USER }}
      M2_PWD: ${{ secrets.M2_PWD }}
      ORG_GRADLE_PROJECT_onstructiveUsername: ${{ secrets.M2_USER }}
      ORG_GRADLE_PROJECT_onstructivePassword: ${{ secrets.M2_PWD }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Prepare
      id: prepare
      run: git fetch --tags

    - name: Publish Jars
      uses: gradle/gradle-build-action@v2
      with:
        arguments: check publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
