name: Release to GitHub Packages

on:
  push:
    branches:
      - '[0-9]+.[0-9]+.x'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    services:
      mail:
        image: mailhog/mailhog
        ports:
          - "8025:8025"
          - "1025:1025"

    env:
      M2_USER: ${{ secrets.M2_USER }}
      M2_PWD: ${{ secrets.M2_PWD }}
      GESUS_ARTIFACTORY_USER: ${{ secrets.M2_USER }}
      GESUS_ARTIFACTORY_PASS: ${{ secrets.M2_PWD }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Prepare
      id: prepare
      run: |
        git config --local user.name "Build"
        git config --local user.email "github@wangler.io"
        git fetch --tags

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Publish
      uses: gradle/gradle-build-action@v2
      with:
        arguments: artifactoryPublish publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish tag
      env:
        TOKEN: ${{ secrets.M2_PWD }}
      run: git push https://saw303:${TOKEN}@github.com/saw303/micronaut-mailhog-client.git --tags
